### ISSUE TITLE
cert/redirect issue_page not loading

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#275] opened 2015-12-29 21:31 UTC
A user writes: 

"Finally got it to sort-of work. I think there are a couple of parts to the problem, but the first is that the cert for the site is for *.zooniverse.org and it isn't recognized for shakespearesworld.org. After I accepted the exception for the cert, I then clicked "Sign in via Zooniverse," which, since I was already logged into zooniverse.org, returned immediately with the Redirect URI error. Not sure what the next step was (sorry!) but eventually I got to a blank page with an auth token in the URI and no redirect_uri field. I manually changed http:// to https:// and now I'm in. I hope this helps isolate the problem."

**Comment by camallen** [comment] 2016-01-04 11:28
duplicate of #274 but with more info. This should be covered by fixing [this issue](https://github.com/zooniverse/shakespeares_world/issues/274#issuecomment-167883051).

**Closed by camallen** 2016-01-04 11:28 UTC
