### ISSUE TITLE
pdfs not rendering properly

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#256] opened 2015-12-10 20:25 UTC
Have seen a complaint on Talk but don't yet know what browser. During beta I saw the problem in FF though. 

User writes: 'I chose to download a PDF version of a page I was transcribing, but when I looked at it, I could only see the first few words of each transcribing textbox as the line went off the page, and each time I had used an abbreviation or expansion button I got the code instead of the word in the textbox. Is there anyway I could get access to the full textbox as it appeared when I saved it?'

Can we retrieve the transcription manually?

**Comment by VVH** [comment] 2015-12-10 20:35
Here's one I just did. 
![screen shot 2015-12-10 at 20 35 06](https://cloud.githubusercontent.com/assets/6482891/11727733/9ac79310-9f7d-11e5-8ba8-d98caed0c741.png)

**Comment by simoneduca** [comment] 2015-12-11 14:10
Duplicate of #137

**Closed by simoneduca** 2015-12-11 14:10 UTC
