### ISSUE TITLE
Deletion button needs to work for all abbreviations in the keypad

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#89] opened 2015-10-13 10:58 UTC
When you press 'wch' and then highlight it to say it has been deleted it does not show up as such. Same is true for everything else along the top line, so far as I can see. There will be cases where something is both an abbreviation and deleted. It works on 'letter' for example, but not wch, wt, etc.

**Comment by simoneduca** [comment] 2015-10-14 15:07
I can't reproduce. Closing it for now.

**Closed by simoneduca** 2015-10-14 15:07 UTC
