### ISSUE TITLE
Snippet misbehaving in Linux mint / chrome

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#251] opened 2015-12-10 17:14 UTC
@ Jules writes: When I click on save nothing happens. Clicking outside the pop-up "save snippet" box gets rid of the box but nothing is added to the crib sheet. I've managed to add one item so far by repeatedly clicking on save and then clicking outside the box.

Linux mint / chrome

**Comment by rogerhutchings** [comment] 2015-12-22 00:27
Dupe of #273

**Closed by rogerhutchings** 2015-12-22 00:27 UTC
