### ISSUE TITLE
Deletion strike through and marginalia highlighting not showing in Safari or Firefox

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#218] opened 2015-12-08 17:27 UTC
The tags are probably being added, but the strike through and colored highlighting isn't working.

**Comment by simoneduca** [comment] 2015-12-09 11:09
This is how transcription markdown is displayed for me on Safari Version 9.0.2.

![screen shot 2015-12-09 at 11 06 16](https://cloud.githubusercontent.com/assets/8989606/11683782/fac88130-9e64-11e5-957a-54dbf5ffe5e5.png)

So I can't reproduce.

@VVH which Safari version are you using?

**Comment by simoneduca** [comment] 2015-12-09 11:20
Same for FF, closing.

**Comment by VVH** [comment] 2015-12-12 18:34
We're having some related issues with 'unclear' etc. As reported on Talk: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20867?comment=42969

**Closed** 2016-02-15 12:27 UTC
