### ISSUE TITLE
Change automatic log out time

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#287] opened 2016-04-04 09:36 UTC
Hey @rogerhutchings we talked about this ~10 days ago and you said you'd a) issue it up and b) implement last Tuesday, but I think that things have been busy. There are ongoing complaints from users on Talk who are losing work on a regular basis because of the 2 hour time out. We get the data, but they don't get to pdf their work. Can you give me a date by which to expect this to be done by adding a milestone to this issue.

**Comment by rogerhutchings** [comment] 2016-04-14 13:39
duplicate of #286

**Closed by rogerhutchings** 2016-04-14 13:39 UTC
