### ISSUE TITLE
cursor should automatically go into transcription box

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#252] opened 2015-12-10 17:20 UTC
a few users and @marten have commented on this and it would be an easy win. I don't see Marten's issue, but it's probably because I'm going crosseyed.

**Comment by rogerhutchings** [comment] 2015-12-11 10:41
Duplicate of #233

**Closed by rogerhutchings** 2015-12-11 10:41 UTC

**Comment by rogerhutchings** [comment] 2015-12-11 10:42
Also, you can search for issues by author: [`author:marten`](https://github.com/zooniverse/shakespeares_world/issues?utf8=%E2%9C%93&q=author%3Amarten+) in the search box
